from __future__ import annotations

"""Guided learning content for Wize Wizard.

The handbook-derived lessons intentionally keep the book's pattern:
plain-English meaning -> logic -> process -> formula -> worked example -> use -> limitations.
Wize-specific lessons (Why ladder, PERT, communications) are labeled as Wize methods.
"""

LESSONS = [
    {
        "slug": "wize-why-ladder",
        "title": "The Wize Why Ladder: Need → Wish → Dream → Fantasy",
        "chapter": "Wize Core Method",
        "minutes": 8,
        "plain_name": "Connected strategic reasoning",
        "acronyms": [],
        "question": "What do I actually need to do, and why does it matter?",
        "why": "Someone who does not yet know what to do needs a concrete next goal and a visible chain of reasons behind it.",
        "process": [
            "Choose one strategic question: What is Winning? Where Will I Play? What Tools Do I Need? What Management System Do I Need? or What Skills Do I Need?",
            "Write the first concrete Need as: I need to ___ so that I can ___.",
            "Ask WHY? Turn the answer into another complete I need to ___ so that I can ___ statement. That becomes Wish / Why 1.",
            "Ask WHY again for Dream / Why 2, then again for Fantasy / Why 3.",
            "Return to the original Need. That is the Goal Wize will PERT-test and turn into execution work.",
        ],
        "concept": "The Why ladder is a Wize Wizard method. It prevents a reason from being stored as a vague fragment. Each level is a complete requirement-and-purpose statement, so the user can trace a concrete Goal back to the larger reason it exists.",
        "formula": "Need (Goal) → WHY? → Wish → WHY? → Dream → WHY? → Fantasy",
        "example": "I need to make money so that I can buy a car → WHY? → I need reliable transportation so that I can get to work → WHY? → I need to buy a house so that I can reduce rent → WHY? → I need financial freedom so that I can control my time.",
        "use_when": "Use this at the beginning of every Wize project and whenever a goal feels arbitrary, disconnected or hard to prioritize.",
        "limitations": "The chain makes reasoning visible; it does not prove that each reason is correct. Challenge assumptions in Clay Tablets and revise the chain when evidence changes.",
        "tool_endpoint": "wizard",
        "tool_label": "Build a Why chain",
        "animation_scene": "WhyLadder",
        "demo": "why",
        "quiz": {"q": "Which level becomes the concrete Goal that receives the PERT test?", "choices": ["Need", "Dream", "Fantasy"], "answer": 0},
    },
    {
        "slug": "wize-pert",
        "title": "PERT and the Wize Stress Test",
        "chapter": "Wize Core Method",
        "minutes": 9,
        "plain_name": "Three-point planning under uncertainty",
        "acronyms": [{"short": "PERT", "long": "Program Evaluation and Review Technique"}],
        "question": "How long could this Goal realistically take, and how much schedule stress is hidden in the estimate?",
        "why": "A single optimistic estimate makes a plan look clearer than it really is. Three-point estimates expose a range and give the Goal a planning envelope.",
        "process": [
            "Select one Need Goal created by the strategy/Why workflow.",
            "Estimate Best Case: what completion looks like if major friction does not occur.",
            "Estimate Most Likely: the ordinary case. Wize can derive the midpoint when using the original shortcut.",
            "Estimate Worst Case: a plausible difficult case, not an impossible disaster scenario.",
            "Calculate the weighted expected value and standard deviation, then review Wize stress bands before committing the Goal.",
        ],
        "concept": "Program Evaluation and Review Technique (PERT) is a three-point estimating method. Wize preserves the original PERT-style calculation and layers a stress interpretation on top so the user can see how uncertainty expands the planning range.",
        "formula": "Expected = (Best + 4×Most Likely + Worst) / 6;  σ = (Worst − Best) / 6",
        "example": "Best 6 hours, Most Likely 12 hours, Worst 24 hours gives a weighted estimate centered toward the likely case while still preserving the uncertainty range.",
        "use_when": "Use it before a Need Goal is marked execution-ready, especially when time, cost or complexity are uncertain.",
        "limitations": "The output is only as useful as the three estimates. False precision in Best/Most Likely/Worst produces false precision in the result.",
        "tool_endpoint": "pert_original",
        "tool_label": "PERT-test a Goal",
        "animation_scene": "PERTStress",
        "demo": "pert",
        "quiz": {"q": "Why use three estimates instead of one?", "choices": ["To expose uncertainty", "To guarantee a deadline", "To eliminate judgment"], "answer": 0},
    },
    {
        "slug": "wize-communications",
        "title": "Communication Channels, Supervisors and Span of Control",
        "chapter": "Wize Core Method",
        "minutes": 9,
        "plain_name": "Designing a manageable team communication structure",
        "acronyms": [],
        "question": "How should the team be grouped so communication does not explode as headcount grows?",
        "why": "All-to-all communication grows quickly as people are added. Wize compares that raw network with managed groups that contain local supervision.",
        "process": [
            "Enter the number of people needed to execute the project.",
            "Calculate raw person-to-person channels with n(n−1)/2.",
            "Create working groups and place at least one local supervisor inside every group with two or more people.",
            "If people remain after grouping, treat the remainder as coordinating managers and recalculate the hierarchy.",
            "Review span of control, management ratio, structured channels and the percentage reduction in communication load.",
        ],
        "concept": "This is a Wize planning heuristic, not a universal management law. Its purpose is to force a deliberate answer to: who coordinates whom, how many direct relationships exist, and whether the structure actually reduces communication complexity.",
        "formula": "Raw channels = n(n−1)/2; Structured channels = local supervisor/member + supervisor coordination + manager oversight",
        "example": "A 10-person all-to-all team has 45 raw channels. A managed structure can reduce the number of coordination paths by using local supervisors and a higher coordination layer when needed.",
        "use_when": "Use it after the Goal and task scope are known and before assigning a multi-person execution team.",
        "limitations": "Real organizations also depend on skill mix, authority, geography, work coupling and communication technology. Channel count is a planning signal, not proof of an ideal org chart.",
        "tool_endpoint": "communications",
        "tool_label": "Design the team",
        "animation_scene": "CommunicationChannels",
        "demo": "comms",
        "quiz": {"q": "What happens to raw all-to-all channels as people are added?", "choices": ["They grow faster than headcount", "They stay constant", "They always equal headcount"], "answer": 0},
    },
    {
        "slug": "strategy-foundations",
        "title": "Strategy: Judgment + Economics + Logic + Computation",
        "chapter": "Handbook Foundations",
        "minutes": 7,
        "plain_name": "Using frameworks as testable lenses",
        "acronyms": [],
        "question": "What must be true for this strategy framework to apply here?",
        "why": "A framework is a lens, not a law. Good strategy makes assumptions visible and testable.",
        "process": ["State the decision you are trying to make.", "Choose a framework only if its assumptions fit the situation.", "Write what must be true for the recommendation to work.", "Test the most decision-relevant uncertainty first.", "Convert the conclusion into a Wize Need: I need to ___ so that I can ___."],
        "concept": "The Strategist's Handbook treats strategy as a combination of judgment, economics, logic and computation. It repeatedly warns against treating named frameworks as universal laws.",
        "formula": "Decision quality ≈ clear assumptions + relevant evidence + coherent action",
        "example": "Instead of writing 'BCG says invest,' record the market-growth assumption, relative market position, cash needs, and what evidence would overturn the recommendation.",
        "use_when": "Use this before every handbook framework and again when a recommendation feels too automatic.",
        "limitations": "No framework is universally valid. Market definition, regulation, turbulence and implementation can reverse a conclusion.",
        "tool_endpoint": "wizard",
        "tool_label": "Convert learning into a Need",
        "animation_scene": "StrategyLoop",
        "demo": "loop",
        "quiz": {"q": "What should you ask before applying a framework?", "choices": ["What must be true for it to apply?", "Which framework is most famous?", "Can I avoid collecting evidence?"], "answer": 0},
    },
    {
        "slug": "bcg-henderson",
        "title": "Henderson, Experience Curves and the BCG Growth-Share Matrix",
        "chapter": "Competitive Position",
        "minutes": 10,
        "plain_name": "Relative competitive position and portfolio allocation",
        "acronyms": [{"short": "BCG", "long": "Boston Consulting Group"}, {"short": "RMS", "long": "Relative Market Share"}],
        "question": "Is our competitive position strong enough to change future cost, cash generation or capital allocation?",
        "why": "The handbook connects cumulative experience, cost position, competitive share and where cash is reinvested.",
        "process": ["Define a reasonably stable competitive market.", "Record your share and the largest competitor's share.", "Calculate Relative Market Share.", "Assess market growth and the portfolio role.", "Check whether experience, cost advantage and cash generation actually support the classification."],
        "concept": "The Boston Consulting Group system links the Experience Curve with relative market position and the Growth-Share Matrix. The matrix uses Stars, Cash Cows, Question Marks and Dogs as portfolio labels, but the handbook treats them as a starting lens rather than a complete decision.",
        "formula": "Relative Market Share = Your Share ÷ Largest Competitor Share",
        "example": "A business with 15% share against a 25% leader has Relative Market Share of 0.60.",
        "use_when": "Use it for portfolio discussions when capital is scarce and businesses differ in growth and competitive position.",
        "limitations": "Two axes cannot capture profitability, disruption, synergies or a badly defined market. The Rule of Three and Four is presented as a heuristic/hypothesis, not a law.",
        "tool_endpoint": "market",
        "tool_label": "Open Market Structure Lab",
        "animation_scene": "BCGExperience",
        "demo": "bcg",
        "quiz": {"q": "15% share against a 25% leader gives what Relative Market Share?", "choices": ["0.60", "1.67", "40"], "answer": 0},
    },
    {
        "slug": "mece-hypothesis",
        "title": "MECE Issue Trees and Hypothesis-Driven Analysis",
        "chapter": "Problem Solving",
        "minutes": 9,
        "plain_name": "Breaking a complex problem into testable branches",
        "acronyms": [{"short": "MECE", "long": "Mutually Exclusive, Collectively Exhaustive"}],
        "question": "How can I break this confusing problem into pieces without obvious gaps or duplicate categories?",
        "why": "Complex problems become easier to test when causes do not overlap unnecessarily and important categories are not omitted.",
        "process": ["Write the decision question in one sentence.", "Split it into non-overlapping branches that collectively cover the problem.", "State a provisional answer for each high-value branch.", "List evidence that would confirm or reject it.", "Test the branch that could most change the decision."],
        "concept": "Mutually Exclusive, Collectively Exhaustive (MECE) is an organizing discipline. Hypothesis-driven analysis starts with a provisional answer, then tests the most decision-relevant uncertainties first.",
        "formula": "Problem = branch₁ + branch₂ + … + branchₙ, without avoidable overlap or gaps",
        "example": "Sales decline → Market / Customer / Economics / Execution. Then test the strongest causal hypothesis inside each branch.",
        "use_when": "Use it when the user knows something is wrong but does not yet know where to investigate first.",
        "limitations": "MECE organizes thinking; it does not prove that the branches or hypotheses are correct.",
        "tool_endpoint": "wizard",
        "tool_label": "Turn a finding into a Need",
        "animation_scene": "MECEIssueTree",
        "demo": "tree",
        "quiz": {"q": "What does MECE aim for?", "choices": ["Coverage without unnecessary overlap", "Maximum number of branches", "A single forecast"], "answer": 0},
    },
    {
        "slug": "five-forces",
        "title": "Porter's Five Forces and Strategic Trade-Offs",
        "chapter": "Industry Structure",
        "minutes": 10,
        "plain_name": "Understanding where industry pressure comes from",
        "acronyms": [],
        "question": "Who can capture value from us besides our direct competitors?",
        "why": "Industry economics depend on rivalry, entrants, substitutes, suppliers and buyers—not only direct competitors.",
        "process": ["Rate rivalry among existing competitors.", "Assess the threat of new entrants.", "Assess the threat of substitute products or services.", "Assess supplier and buyer bargaining power.", "Choose a coherent position and explicitly record what you will not do."],
        "concept": "Porter's Five Forces are rivalry among existing competitors, threat of new entrants, threat of substitutes, bargaining power of suppliers and bargaining power of buyers. Porter also emphasizes trade-offs: a strategy becomes clearer when it specifies what not to do.",
        "formula": "Industry pressure = rivalry + entrants + substitutes + supplier power + buyer power",
        "example": "A merger may reduce direct rivalry, but the resulting firm may still face stronger buyers, new substitutes or aggressive entry.",
        "use_when": "Use it when choosing where to compete, evaluating an industry or rechecking a market after a major move.",
        "limitations": "It is a structural lens. It does not replace customer research, execution analysis or analysis of rapid disruption.",
        "tool_endpoint": "strategy",
        "tool_label": "Apply in Strategy Lab",
        "animation_scene": "FiveForces",
        "demo": "forces",
        "quiz": {"q": "Which is NOT one of Porter's Five Forces?", "choices": ["Employee satisfaction", "Buyer power", "Threat of substitutes"], "answer": 0},
    },
    {
        "slug": "market-structure",
        "title": "Four-Firm Concentration Ratio, Herfindahl-Hirschman Index, Leader Gap and Rank Velocity",
        "chapter": "Market Mathematics",
        "minutes": 12,
        "plain_name": "Measuring how concentrated a market is and how competitive rank changes",
        "acronyms": [{"short": "CR4", "long": "Four-Firm Concentration Ratio"}, {"short": "HHI", "long": "Herfindahl-Hirschman Index"}],
        "question": "How much of the market is controlled by the largest firms, and how far are we from the leader?",
        "why": "A market-share table becomes more useful when it is converted into concentration and movement measures.",
        "process": ["Enter all known competitor market shares.", "Sort firms from largest to smallest.", "Add the four largest shares to get the Four-Firm Concentration Ratio.", "Square each share and add the results to get the Herfindahl-Hirschman Index.", "Track leader gap and rank over time; do not treat concentration alone as proof of profitability."],
        "concept": "The Four-Firm Concentration Ratio adds the shares of the four largest firms. The Herfindahl-Hirschman Index squares every firm's share before adding them, which makes large firms count more heavily. Leader Gap is the share distance from the market leader. Rank Velocity measures movement in competitive rank.",
        "formula": "Four-Firm Concentration Ratio = s₁+s₂+s₃+s₄; Herfindahl-Hirschman Index = Σ(share²); Leader Gap = leader share − your share",
        "example": "Shares of 25%, 20%, 15%, 10% and 7% produce a Four-Firm Concentration Ratio of 70%. Their partial Herfindahl-Hirschman Index is 1,399 before adding any remaining firms.",
        "use_when": "Use it for market-structure analysis, competitive ranking and acquisition scenarios.",
        "limitations": "Market definition matters enormously. These measures do not directly measure profitability, innovation or customer welfare.",
        "tool_endpoint": "market",
        "tool_label": "Calculate market structure",
        "animation_scene": "MarketConcentration",
        "demo": "market",
        "quiz": {"q": "Why does the Herfindahl-Hirschman Index emphasize large firms?", "choices": ["Market shares are squared", "Only the largest firm is counted", "It uses revenue instead of market share"], "answer": 0},
    },
    {
        "slug": "value-creation",
        "title": "Return on Invested Capital, Cost of Capital, Economic Profit, NPV and IRR",
        "chapter": "Corporate Finance",
        "minutes": 13,
        "plain_name": "Testing whether growth actually creates economic value",
        "acronyms": [
            {"short": "ROIC", "long": "Return on Invested Capital"}, {"short": "WACC", "long": "Weighted Average Cost of Capital"},
            {"short": "NOPAT", "long": "Net Operating Profit After Tax"}, {"short": "NPV", "long": "Net Present Value"}, {"short": "IRR", "long": "Internal Rate of Return"},
        ],
        "question": "Are we earning enough on the capital tied up in this decision to justify its financing cost?",
        "why": "Growth can look successful in revenue terms while destroying economic value if operating returns do not cover the cost of capital.",
        "process": ["Estimate Net Operating Profit After Tax and invested capital.", "Calculate Return on Invested Capital.", "Estimate the Weighted Average Cost of Capital.", "Compare the return against the cost of capital and calculate economic profit.", "For project cash flows, also use Net Present Value and Internal Rate of Return while checking their assumptions."],
        "concept": "Return on Invested Capital measures after-tax operating profit relative to capital used. Weighted Average Cost of Capital is the blended required return of debt and equity financing. The handbook's core relationship is that Return on Invested Capital above the cost of capital suggests potential economic value creation; below it suggests potential value destruction.",
        "formula": "Return on Invested Capital = Net Operating Profit After Tax ÷ Invested Capital; Economic Profit = Net Operating Profit After Tax − (Invested Capital × Weighted Average Cost of Capital)",
        "example": "$120 million of Net Operating Profit After Tax on $1 billion of invested capital gives 12% Return on Invested Capital. At 9% cost of capital, economic profit is $30 million.",
        "use_when": "Use it for capital allocation, projects, acquisitions and any strategy that consumes meaningful capital.",
        "limitations": "Inputs can be noisy. Internal Rate of Return can mislead with unusual cash flows, mutually exclusive projects or unrealistic reinvestment assumptions.",
        "tool_endpoint": "finance",
        "tool_label": "Open Value Creation Lab",
        "animation_scene": "ROICvsWACC",
        "demo": "finance",
        "quiz": {"q": "Which condition suggests potential economic value creation?", "choices": ["Return on Invested Capital > Weighted Average Cost of Capital", "Return on Invested Capital < Weighted Average Cost of Capital", "Revenue > assets"], "answer": 0},
    },
    {
        "slug": "risk-monte-carlo",
        "title": "Expected Value, Decision Trees and Monte Carlo Simulation",
        "chapter": "Decision Science and Risk",
        "minutes": 12,
        "plain_name": "Planning with ranges instead of a single forecast",
        "acronyms": [{"short": "EV", "long": "Expected Value"}],
        "question": "What range of outcomes is plausible, and how likely is the decision to succeed or fail?",
        "why": "A single forecast hides uncertainty. The handbook recommends probability-weighted thinking and repeated simulation when inputs are uncertain.",
        "process": ["List uncertain outcomes or inputs.", "Assign reasonable probabilities or distributions.", "Calculate Expected Value or simulate many trials.", "Inspect percentiles and probability of failure/success.", "Size the decision so a positive Expected Value does not require risking the entire enterprise."],
        "concept": "Expected Value multiplies each outcome by its probability and adds the results. Decision trees map choices, chance events and payoffs. Monte Carlo Simulation repeatedly samples uncertain inputs to reveal a distribution rather than a single point forecast.",
        "formula": "Expected Value = Σ(probability × outcome value)",
        "example": "A 60% chance of +$100 million and a 40% chance of −$50 million gives an Expected Value of +$40 million.",
        "use_when": "Use it when outcomes, costs, schedules, margins or competitor reactions are uncertain.",
        "limitations": "Simulation quality is limited by the assumptions and distributions supplied. A model can be precise and still be wrong.",
        "tool_endpoint": "risk",
        "tool_label": "Run the Monte Carlo Lab",
        "animation_scene": "MonteCarloRisk",
        "demo": "risk",
        "quiz": {"q": "What does Monte Carlo Simulation add beyond a base case?", "choices": ["A distribution of plausible outcomes", "Guaranteed accuracy", "A fixed market share"], "answer": 0},
    },
    {
        "slug": "constraints-flow",
        "title": "Theory of Constraints, Little's Law, Queues and PDSA",
        "chapter": "Operations",
        "minutes": 11,
        "plain_name": "Finding the bottleneck and improving flow",
        "acronyms": [{"short": "PDSA", "long": "Plan-Do-Study-Act"}],
        "question": "What single constraint is limiting the whole system, and what happens if we improve everything else first?",
        "why": "Improving non-bottlenecks can create activity without improving total system throughput.",
        "process": ["Identify the system constraint.", "Exploit the constraint with existing resources.", "Subordinate other work to the constraint.", "Elevate the constraint if needed.", "Repeat after the bottleneck moves, using Plan-Do-Study-Act to learn from changes."],
        "concept": "Goldratt's Theory of Constraints focuses improvement on the bottleneck. Little's Law links average work-in-process, throughput and flow time. Queueing analysis warns that waiting time can rise sharply as utilization approaches 100%. Plan-Do-Study-Act is a cycle for testing and learning from changes.",
        "formula": "Little's Law: average items in system = throughput rate × average time in system",
        "example": "If 20 jobs per day flow through a stable process and each spends 3 days in it, average work-in-process is about 60 jobs.",
        "use_when": "Use it when work is piling up, lead times are long, teams are busy but output is not improving, or one resource repeatedly blocks progress.",
        "limitations": "Little's Law relies on stable long-run averages. Real queue behavior depends on arrival and service patterns, and the apparent bottleneck may move after improvement.",
        "tool_endpoint": "tasks",
        "tool_label": "Review execution tasks",
        "animation_scene": "ConstraintsFlow",
        "demo": "flow",
        "quiz": {"q": "What should be improved first in Theory of Constraints?", "choices": ["The bottleneck", "Every activity equally", "The busiest-looking employee"], "answer": 0},
    },
    {
        "slug": "integrated-case",
        "title": "Integrated Strategy Case: From Market Position to a Full Decision",
        "chapter": "Capstone",
        "minutes": 15,
        "plain_name": "Combining frameworks instead of stopping at one metric",
        "acronyms": [{"short": "CR4", "long": "Four-Firm Concentration Ratio"}, {"short": "HHI", "long": "Herfindahl-Hirschman Index"}, {"short": "ROIC", "long": "Return on Invested Capital"}, {"short": "WACC", "long": "Weighted Average Cost of Capital"}],
        "question": "Does this move improve competitive position and still create value after costs, reactions, risk and future options are considered?",
        "why": "The handbook's integrated case demonstrates that market share alone is not enough to justify an acquisition or strategic move.",
        "process": ["Check whether Henderson's market-structure heuristic is relevant.", "Calculate concentration and competitive rank.", "Simulate the acquisition and rerank firms.", "Test purchase price, integration cost, synergies, Return on Invested Capital and cost of capital.", "Rerun Porter's Five Forces and model uncertain outcomes with Monte Carlo Simulation.", "Finish by checking whether current investment is crowding out future growth options through the Three Horizons lens."],
        "concept": "The handbook combines Henderson/BCG, concentration measures, acquisition re-ranking, value creation, growth decomposition, Porter's Five Forces, Monte Carlo Simulation and the Three Horizons of Growth. The point is to connect lenses, not to let one formula make the decision.",
        "formula": "Decision = competitive position + economics + competitor response + uncertainty + future options",
        "example": "If a 10% #4 firm buys a 7% #5 firm, it reaches 17% and becomes #3—but the handbook says to continue into price, integration, synergies, financing, Return on Invested Capital, cost of capital, competitor response and regulatory constraints.",
        "use_when": "Use it as the capstone before finalizing a major strategic move or the Wize final project plan.",
        "limitations": "The case is illustrative. Real analysis requires complete market data, credible financial inputs, customer evidence and regulatory review.",
        "tool_endpoint": "reports",
        "tool_label": "Build the Final Project Plan",
        "animation_scene": "IntegratedDecision",
        "demo": "integrated",
        "quiz": {"q": "After a target improves your competitive rank, what comes next?", "choices": ["Test whether the deal creates value and survives broader analysis", "Stop the analysis", "Ignore competitor response"], "answer": 0},
    },
]

LESSON_MAP = {x["slug"]: x for x in LESSONS}

# Handbook-based prompts used in the final project plan. These are prompts/checks, not automatic conclusions.
FINAL_PLAN_TIPS = [
    {"title": "Challenge the framework", "tip": "Ask: What must be true for this framework to apply here? Record evidence that could overturn the recommendation."},
    {"title": "Make trade-offs explicit", "tip": "A coherent strategy should say what the project will not do, not only what it will do."},
    {"title": "Check competitive structure", "tip": "If market position matters, define the market carefully and examine concentration, relative position and competitor response rather than using share alone."},
    {"title": "Check value creation", "tip": "If the project consumes material capital, compare operating return on capital with the cost of that capital and examine discounted cash-flow economics."},
    {"title": "Model uncertainty", "tip": "Do not rely on one forecast when important inputs are uncertain. Use ranges, probabilities, decision trees or Monte Carlo Simulation where appropriate."},
    {"title": "Find the constraint", "tip": "Identify the bottleneck that limits the whole system before spending effort optimizing non-constraints."},
    {"title": "Protect future options", "tip": "Use the Three Horizons lens to check whether today's project is consuming all attention and capital while future growth options are neglected."},
    {"title": "Learn after execution", "tip": "Use Plan-Do-Study-Act and the Wize Journal/Clay Tablets to compare assumptions with what actually happened and revise the next strategy pass."},
]
